### ISSUE TITLE
No longer getting data from PosLaju

### ISSUE THREAD

**Issue by khoking** [afzafri/Poslaju-Tracking-API#3]
I have applied the changes you made in Jan 2018, but still there is no data obtained from PosLaju and is always RECORD NOT FOUND.

**Comment by nusrohdeveloper** [comment]
Seriously???

**Comment by afzafri** [comment]
Hi, looks like poslaju made some modifications to their tracking website again. I will try to look at it once I finished my examination.

**Comment by nusrohdeveloper** [comment]
Terbaik bro. Terima kasih.

**Comment by afzafri** [comment]
Hi, I already tested the script, it's working fine now. If still show ```RECORD NOT FOUND```, it either because of the tracking number is expired, or the tracking info still not in the system. 
I have updated the ```demo.php``` file with new tracking number to try.
