### ISSUE TITLE
Poslaju Tracking API

### ISSUE THREAD

**Issue by pakngah** [afzafri/Poslaju-Tracking-API#8]
Need to update for poslaju tracking api, thank you.

**Comment by zfc0812** [comment]
Pos Malaysia has changed their website and currently the API is no longer working. Just a suggestion, perhaps it will be easier to scrape the tracking data from https://www.tracking.my/poslaju instead of pos laju website?

**Comment by zfc0812** [comment]
@afzafri please help. Really in need of this API.

**Comment by afzafri** [comment]
> Pos Malaysia has changed their website and currently the API is no longer working. Just a suggestion, perhaps it will be easier to scrape the tracking data from https://www.tracking.my/poslaju instead of pos laju website?

Not easy. Tracking.my use AJAX to their backend API to get the result. And their API is protected with their API auth and CSRF protection.

**Comment by mafsa7** [comment]
1. Set to new url with trackingNo get/request 
`$url = "https://sendparcel.poslaju.com.my/open/trace?tno={$trackingNo}";`

2. Change to CURL GET

```
$ch = curl_init();
curl_setopt($ch, CURLOPT_URL, $url);
curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
curl_setopt($ch, CURLOPT_SSL_VERIFYHOST, false); 
curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, false); 
$result = curl_exec($ch); 
$httpstatus = curl_getinfo($ch, CURLINFO_HTTP_CODE); 
$errormsg = (curl_error($ch)) ? curl_error($ch) : "No error"; 
curl_close($ch); 
```
	
3. Set Pattern
`$patern = "/<table.*?>(.*?)<\/table>/si";`

**Comment by afzafri** [comment]
Hi @mafsa7 , thank you for the code snippet. Currently I am quite busy with my daily commitments, if you have time you can fork this repo and perform a pull request. I will merge into the repo.

**Comment by mafsa7** [comment]
dah

**Comment by afzafri** [comment]
terbaik bos dah merge
